### ISSUE TITLE
Problem when importing AdaGram

### ISSUE THREAD

**Issue by ClaudeCoulombe** [lopuhin/python-adagram#10]
I've got problem when trying to import AdaGram, Python 3.6.0a2 on Mac OS 10.12.5
Where is the clearn module?

>>> import adagram
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/claudecoulombe/git/AdaGram-python/adagram/__init__.py", line 1, in <module>
    from adagram.model import Dictionary, VectorModel
  File "/Users/claudecoulombe/git/AdaGram-python/adagram/model.py", line 11, in <module>
    from .learn import inplace_train
  File "/Users/claudecoulombe/git/AdaGram-python/adagram/learn.py", line 10, in <module>
    from . import clearn
ImportError: cannot import name 'clearn'

**Comment by lopuhin** [comment]
@ClaudeCoulombe clearn module should have been compiled when you run ``pip install git+https://github.com/lopuhin/python-adagram.git``, or ``pip install  -e .`` if you cloned first, or ``python setup.py install``. Do you still have a log from the installation around?

**Comment by ClaudeCoulombe** [comment]
It works with `sudo pip3 install git+https://github.com/lopuhin/python-adagram.git` Fine!

But it's still not working when I clone the repo first with `git clone https://github.com/lopuhin/python-adagram.git` then install with `sudo python3 setup.py install`

```
In file included from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
adagram/clearn.c:2539:536: warning: incompatible pointer types passing '__pyx_t_5numpy_int32_t *' (aka 'long *') to parameter of type 'int32_t *'
      (aka 'int *') [-Wincompatible-pointer-types]
  ...)))), __pyx_v_w, (&(*((__pyx_t_5numpy_int32_t *) ( /* dim=0 */ (__pyx_v_context.data + __pyx_t_14 * __pyx_v_context.strides[0]) )))), __pyx_t_...                    
```
There is no such errors with `sudo python setup.py install` but I still have `ImportError: cannot import name 'clearn'` when I try to import adagram `>>> import adagram`
