### ISSUE TITLE
the meaning of function  `word_sense_probs`

### ISSUE THREAD

**Issue by mahao01** [lopuhin/python-adagram#15]
I saw comments  say that `word_sense_probs ` returns sense probabilities for given word. Does it mean the  percentage of the sense in the training corpus? 
For example, `word_sense_probs('apple')` returns `[0.34, 0.66]`, it means 34% of word `apple` hold the first sense and 66% hold the second sense?

**Comment by lopuhin** [comment]
@mahao01 yes, this is correct: this function returns prior probabilities which should correspond to the ratios of senses in the corpus.

**Comment by lopuhin** [comment]
Just a small correction: ``word_sense_probs('apple')`` should return the indices as well, so something like ``[(0, 0.34), (1, 0.66)]``

**Comment by mahao01** [comment]
Thanks for your reply.

**Comment by lopuhin** [comment]
@mahao01 you're welcome!
