### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mojesty** [lopuhin/python-adagram#5]
I have a problem when trying to run `pip install python-adagram` command on py2.7 osX: pip says

>   Could not find a version that satisfies the requirement adagram (from versions: )
No matching distribution found for adagram

In the [PyPI list](https://pypi.python.org/pypi?%3Aaction=search&term=python-adagram&submit=search) there's nothing about adagram. Could something be done of it?

**Comment by lopuhin** [comment]
Right, I still didn't put it on PyPI yet - just need to package it properly. For now you can install from source - you can use the following commands:
```
pip install Cython numpy
pip install git+https://github.com/lopuhin/python-adagram.git
```

**Comment by lopuhin** [comment]
The issue about pypi upload is #2

**Comment by lopuhin** [comment]
@mojesty also note that training is not working correctly yet - so it's recommended to train with AdaGram.jl and then convert the model. Just reworded note at the start of README to make it more clear.
